
#???8080
server:
  port: 8080

#?????mysql????root???123456
spring:
  jpa:
    open-in-view: false

  datasource:
    username: root
    password: Dongxiaouo88
    #password: abc123
    url: jdbc:mysql://localhost:3306/pet
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: org.example.petspringdemo.entity

#showSql
logging:
  level:
    com.example.demo.mapper: debug
